URL_MAPPING = {
    "100 college representatives to visit St. Margaret’s": "https://www.smes.org/news-detail?pk=1348401",
    "100 college representatives who visit St. Margaret’s": "https://www.smes.org/news-detail?pk=1348401",
    "2024 St. Margaret’s Summer Institute": "https://www.smes.org/news-detail?pk=1339200",
    "2025 State of School – See the Recap!": "https://www.smes.org/page/news-detail?pk=1366666&fromId=295807",
    "2025-2026 School Tuition": "http://www.smes.org/page/admission/tuition-and-financial-support",
    "40th Commencement Exercises": "http://www.smes.org/page/event-detail?pk=20884366&fromId=289709",
    "7 Tartans Honored for Writing Excellence by NCTE": "https://www.smes.org/page/news-detail?pk=1383463&fromId=289710",
    "7/8 Boys Lacrosse Repeats as PAL Champions in Thrilling 13-12 Overtime Win": "https://www.smes.org/page/news-detail?pk=1369970&fromId=289710",
    "ARTS PROGRAMS": "http://www.smes.org/about/ptf",
    "About": "https://www.smes.org/about",
    "About Summer at St. Margaret's": "https://www.smes.org/community/summer-at-st-margarets/about-summer-at-st-margarets",
    "Academic Classes": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Academic Departments": "https://www.smes.org/academics/academic-program/academic-departments",
    "Academic Program": "https://www.smes.org/academics/academic-program",
    "Academics": "https://www.smes.org/academics",
    "Add to Cart": "http://www.smes.org/page/tartan-store",
    "Additional Information": "http://www.smes.org/page/tartan-store",
    "Admission": "https://www.smes.org/admission",
    "Admission Events Calendar": "http://www.smes.org/page/admission-calendar",
    "Advanced Placement Music Theory": "http://www.smes.org/student-life/arts/performing-arts",
    "Advisory": "https://www.smes.org/student-life/advisory",
    "Alanna Cajthaml, Chief Financial and Operating Officer": "http://www.smes.org/about/leadership",
    "Alethea Monge": "http://www.smes.org/about/leadership",
    "All-School service": "https://www.smes.org/news-detail?pk=1358745&fromId=289710",
    "Alumni": "https://www.smes.org/alumni",
    "Amaya Christensen Seals 1-0 Victory for Tartan Girls Soccer": "https://www.smes.org/page/news-detail?pk=1368672&fromId=289710",
    "Amy Roberts, Upper School Principal": "http://www.smes.org/about/leadership",
    "Amy Warren, Director of College Counseling": "http://www.smes.org/about/leadership",
    "Angela Mackenzie, Director Educational Technology and Library": "http://www.smes.org/about/leadership",
    "Annual Fund": "https://www.smes.org/support-smes/annual-fund",
    "Apply": "https://www.smes.org/page/admission/apply",
    "Apply Online": "https://www.smes.org/page/admission/apply",
    "Apply for Financial Aid": "http://www.smes.org/page/admission/tuition-and-financial-support",
    "Are there language requirements for non-native English speakers?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Arts": "https://www.smes.org/student-life/arts",
    "Arts Events": "https://www.smes.org/page/student-life/arts",
    "At a Glance": "https://www.smes.org/admission/at-a-glance",
    "Athletic Camps": "https://www.smes.org/community/summer-at-st-margarets/open-enrollment-camps/athletic-camps",
    "Athletic Events": "https://www.smes.org/page/student-life/athletics",
    "Athletics": "https://www.smes.org/student-life/athletics",
    "Attendance and Credit Policy": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "BOOSTERS PROGRAM": "http://www.smes.org/about/ptf",
    "Band": "http://www.smes.org/student-life/arts/performing-arts",
    "Benn McCallister": "http://www.smes.org/about/leadership",
    "Bernard E. Schneider, Treasurer": "http://www.smes.org/about/leadership",
    "Boys Basketball Downs University 62-54": "https://www.smes.org/page/news-detail?pk=1368552&fromId=289710",
    "Boys Lacrosse Dispatches Trojans 16-4": "https://www.smes.org/page/news-detail?pk=1372684&fromId=289710",
    "Boys Soccer is Playoff Bound With 1-0 Win Over University": "https://www.smes.org/page/news-detail?pk=1368671&fromId=289710",
    "Boys Tennis and Girls Lacrosse Open Spring Campaigns With Wins": "https://www.smes.org/page/news-detail?pk=1371703&fromId=289710",
    "Boys Volleyball Blanks Timberwolves 3-0": "https://www.smes.org/page/news-detail?pk=1375260&fromId=289710",
    "Boys Volleyball Sweeps Portola 3-0": "https://www.smes.org/page/news-detail?pk=1377177&fromId=289710",
    "Boys Volleyball on to Semifinals With 3-1 Win Over Burroughs": "https://www.smes.org/page/news-detail?pk=1381649&fromId=289710",
    "Breakthrough Endowment": "http://www.smes.org/support-smes/endowed-funds",
    "Breakthrough San Juan Capistrano": "http://www.smes.org/support-smes/guide-to-philanthropy",
    "Bring Your Own Device": "https://www.smes.org/academics/upper-school/bring-your-own-device",
    "CIF Team Champions and Finalists": "http://www.smes.org/student-life/athletics/championships-and-awards",
    "Calendar": "https://www.smes.org/page/calendar",
    "Camp Hours": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Campus Technology": "http://www.smes.org/innovation/steam-and-technology/technology-for-teaching-and-learning",
    "Campus Tours": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Can I request my child to be in the same group as their friend?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Cancellations after May 1, 2025": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Cancellations before May 1, 2025": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Cancellations by Summer at St. Margaret's": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Candlelighting Ceremony Symbolizes Passing of Leadership in Upper School": "https://www.smes.org/page/news-detail?pk=1380809&fromId=289710",
    "Cash or Credit Card": "http://www.smes.org/page/support-smes/giving",
    "Cathleen Stahl, Vice President": "http://www.smes.org/about/leadership",
    "Chair-ish our Tartans": "https://www.smes.org/chair-ish-our-tartans",
    "Champions! Girls Lacrosse Claims CIF-SS Title With 11-8 Win": "https://www.smes.org/page/news-detail?pk=1383068&fromId=289710",
    "Championships and Awards": "https://www.smes.org/student-life/athletics/championships-and-awards",
    "Chapel": "https://www.smes.org/student-life/chapel",
    "Chase Heger Endowment": "http://www.smes.org/support-smes/endowed-funds",
    "Check Email": "https://email.smes.org/",
    "Choir": "http://www.smes.org/student-life/arts/performing-arts",
    "Class Retreats": "https://www.smes.org/innovation/experiential-learning/class-retreats",
    "Class of 2024 Enjoying Early Success in College-Admissions Process": "http://www.smes.org/page/news-detail?pk=1320903&fromId=289859",
    "Class of 2024 Meet With College Representatives as Application Process Begins": "http://www.smes.org/page/news-detail?pk=1294543&fromId=289859",
    "Class of 2025 Enjoying Early Success in the College-Admissions Process": "https://www.smes.org/page/news-detail?pk=1369686&fromId=289710",
    "Class of 2025 Meet With College Representatives as Application Process Begins": "http://www.smes.org/page/news-detail?pk=1348401&fromId=289859",
    "Class of 2026 Explores San Diego Universities on College Tour": "https://www.smes.org/page/news-detail?pk=1384369&fromId=289710",
    "Class of 2029 Celebrates Grade 8 Promotion": "https://www.smes.org/page/news-detail?pk=1384822&fromId=289710",
    "Clear All": "https://www.smes.org/page/about/news",
    "Click here to read more about how we are engaging in DEI work at St. Margaret's": "https://www.smes.org/page/innovation/diversity-equity-and-inclusion",
    "Coaches and Staff": "https://www.smes.org/student-life/athletics/coaches-and-staff",
    "College Counseling": "https://www.smes.org/page/academics/academic-program/college-counseling",
    "College Counseling Program": "https://www.smes.org/page/academics/academic-program/college-counseling",
    "College Counseling Team Meets With Class of 2026 and Families": "http://www.smes.org/page/news-detail?pk=1361480&fromId=289859",
    "College Matriculation Map": "https://www.smes.org/academics/academic-program/college-counseling/college-matriculation-map",
    "Community": "https://www.smes.org/community/community",
    "Computer Science": "https://www.smes.org/page/academics/academic-program/academic-departments",
    "Computer Science Students Attend UCI Creative Edge Lecture": "https://www.smes.org/page/news-detail?pk=1374465&fromId=289710",
    "Computer Science and Engineering": "https://www.smes.org/innovation/steam-and-technology/computer-science-and-engineering",
    "Connect With Us": "https://www.smes.org/admission/connect-with-us",
    "Cross-Divisional Project Inspires Curiosity for Space Exploration": "https://www.smes.org/page/news-detail?pk=1375654&fromId=289710",
    "Cross-Divisional Project Sparks Curiosity for the Space Exploration Exhibit": "https://www.smes.org/page/news-detail?pk=1326696&fromId=290012",
    "Curriculum": "https://www.smes.org/academics/early-school/curriculum",
    "DEI and cultural competency work": "https://www.smes.org/innovation/diversity-equity-and-inclusion",
    "Daily Essentials": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Dan Pacheco, Director of Performing Arts": "http://www.smes.org/about/leadership",
    "Dana Sullivan, President": "http://www.smes.org/about/leadership",
    "Daniel O'Shea, Director of Athletics": "http://www.smes.org/about/leadership",
    "Dates": "https://www.smes.org/community/summer-at-st-margarets/about-summer-at-st-margarets/dates",
    "David Bush, Trustee Emeritus": "http://www.smes.org/about/leadership",
    "Day Camps": "https://www.smes.org/community/summer-at-st-margarets/open-enrollment-camps/day-camps",
    "Directory": "https://www.smes.org/page/directory",
    "Diversity, Equity and Inclusion": "https://www.smes.org/innovation/diversity-equity-and-inclusion",
    "Do I have to sign my child in and out daily?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Do I pack lunch and snacks or does camp provide food?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Does my child have to be potty trained?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Donate Now": "http://www.smes.org/page/online-giving",
    "Dr. Cris Lozon, Director of the Early Childhood School & Wee Tartan Center": "http://www.smes.org/about/leadership",
    "Dr. Jeneen D. Graham, Head of School": "http://www.smes.org/about/leadership",
    "Dr. Maryam Kia-Keating, Director of Counseling": "http://www.smes.org/about/leadership",
    "Dr. Ryan Carey, Director of Extensions and Experiential Education": "http://www.smes.org/about/leadership",
    "Dr. Stephanie Capen, Director of Institutional Research": "http://www.smes.org/about/leadership",
    "Dramatic Play/Drama": "https://www.smes.org/page/academics/early-school/curriculum",
    "Early Childhood": "http://www.smes.org/student-life/arts/performing-arts",
    "Early Childhood Educators Share Innovative Approaches at NAEYC Conference": "https://www.smes.org/page/news-detail?pk=1357278&fromId=290012",
    "Early School": "https://www.smes.org/academics/early-school",
    "Early School Begins School Year of Play-Based Learning": "https://www.smes.org/page/news-detail?pk=1342914&fromId=290012",
    "Early School Camps": "https://www.smes.org/community/summer-at-st-margarets/open-enrollment-camps/early-school-camps",
    "Early School Garden Undergoes Exciting Transformation": "https://www.smes.org/page/news-detail?pk=1381586&fromId=289710",
    "Early School Students Build Foundation for Literacy Through Play-Based Learning": "https://www.smes.org/page/news-detail?pk=1348363&fromId=290012",
    "Early School Teachers Attend Renowned Reggio Emilia Study Group": "https://www.smes.org/page/news-detail?pk=1328726&fromId=290012",
    "Early School Teachers Prepare for New Music Curriculum With Visit to Fender": "https://www.smes.org/page/news-detail?pk=1342063&fromId=290012",
    "Early School Teachers Present at Caltech’s ECSTEM Conference": "https://www.smes.org/page/news-detail?pk=1323259&fromId=290012",
    "Early School’s WOW Night Celebrates a School Year of Meaningful Learning": "https://www.smes.org/page/news-detail?pk=1330123&fromId=290012",
    "Early School’s WOW Night Showcases and Celebrates Student Learning": "https://www.smes.org/page/news-detail?pk=1379596&fromId=289710",
    "Electronics and Cell Phones": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Emma Perry '11, R. N., Lead School Nurse": "http://www.smes.org/about/leadership",
    "Employment": "https://www.smes.org/page/about/employment",
    "Employment Inquiry": "https://www.smes.org/about/employment/employment-inquiry",
    "Endowed Funds": "https://www.smes.org/support-smes/endowed-funds",
    "English": "https://www.smes.org/page/academics/academic-program/academic-departments",
    "Episcopal identity": "https://www.smes.org/about/mission/",
    "Equity and Inclusion": "https://www.smes.org/about/equity-and-inclusion",
    "Ernest D. Sillers Legacy Society": "https://www.smes.org/support-smes/giving",
    "Events": "https://www.smes.org/admission-calendar?siteId=1699",
    "Exceptional Student Artwork Showcased at the Barbara Nelson Exhibit": "https://www.smes.org/page/news-detail?pk=1378266&fromId=289710",
    "Experiential Learning": "https://www.smes.org/innovation/experiential-learning",
    "Exploration and Specialty Camps": "https://www.smes.org/community/summer-at-st-margarets/open-enrollment-camps/exploration-and-specialty-camps",
    "Explore": "https://www.smes.org/",
    "Explore the Strategic Plan and Progress Reports": "http://www.smes.org/page/strategic-plan",
    "Extended Day": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "FOREVER PLAID": "http://www.smes.org/about/ptf",
    "FRIENDS OF THE LIBRARY PROGRAM": "http://www.smes.org/about/ptf",
    "Fall 2024": "https://www.smes.org/strategic-plan",
    "Fees": "https://www.smes.org/community/summer-at-st-margarets/about-summer-at-st-margarets/fees",
    "Financial Aid - SMES Families Only": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "First Day of Early Childhood School": "https://www.smes.org/page/event-detail?pk=23330333&fromId=289703",
    "First Day of School Grades K-12": "https://www.smes.org/page/event-detail?pk=23330300&fromId=289703",
    "Five Tartans Garner Winter Sports Post-Season Accolades": "https://www.smes.org/page/news-detail?pk=1377393&fromId=289710",
    "For St. Margaret's Students": "https://www.smes.org/community/summer-at-st-margarets/for-st-margarets-students",
    "Ford Endowment": "http://www.smes.org/support-smes/endowed-funds",
    "FrightFEST Puts Talented Tartan Artists in the Spotlight": "https://www.smes.org/page/news-detail?pk=1355128&fromId=289897",
    "GRADE LEVEL COFFEES": "http://www.smes.org/about/ptf",
    "GRANT ENRICHMENT PROGRAM": "http://www.smes.org/about/ptf",
    "Gabriella Eifrig '24 Recognized as BIG EAST Female Golfer of the Week": "https://www.smes.org/page/news-detail?pk=1377381&fromId=289710",
    "Gear-Up Classes": "https://www.smes.org/community/summer-at-st-margarets/for-st-margarets-students/gear-up-classes",
    "General Contact Information": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "General Endowment": "http://www.smes.org/support-smes/endowed-funds",
    "Get Involved!": "https://www.smes.org/alumni/get-involved",
    "Getting to St. Margaret's": "https://www.smes.org/admission/getting-to-st-margarets",
    "Gifts in-kind": "http://www.smes.org/page/support-smes/giving",
    "Girls Beach Volleyball Punches Ticket to Playoffs with 5-0 Sweep of Irvine": "https://www.smes.org/page/news-detail?pk=1378474&fromId=289710",
    "Girls Lacrosse Cruises in 15-3 win Over Portola": "https://www.smes.org/page/news-detail?pk=1378396&fromId=289710",
    "Girls Lacrosse Sneaks By Woodbridge 15-14": "https://www.smes.org/page/news-detail?pk=1374706&fromId=289710",
    "Girls Lacrosse is Finals Bound after 13-11 Win": "https://www.smes.org/page/news-detail?pk=1381997&fromId=289710",
    "Give to SMES": "https://www.smes.org/page/support-smes/giving",
    "Give to TALE": "http://www.smes.org/page/tartan-alumni-legacy-endowment",
    "Giving": "https://www.smes.org/support-smes/giving",
    "Grade 2 Student Historians Explore What It Means to Be a Hero": "https://www.smes.org/page/news-detail?pk=1383223&fromId=289710",
    "Grade 2 Students Dive Into Outdoor Learning at Crystal Cove Tide Pools": "https://www.smes.org/page/news-detail?pk=1379245&fromId=289710",
    "Grade 3 Students Explore Composting in Hands-On Learning Experience": "https://www.smes.org/page/news-detail?pk=1377417&fromId=289710",
    "Grade 3 Students Lead Tartan Participation in FAM Hunger Walk": "https://www.smes.org/page/news-detail?pk=1352161&fromId=289710",
    "Grade 4 Students Embark on Field Trip to Deepen Learning of California History": "https://www.smes.org/page/news-detail?pk=1367262&fromId=289710",
    "Grade 4 Students Light Up Their Learning with Lighthouse Project": "https://www.smes.org/page/news-detail?pk=1366180&fromId=289710",
    "Grade 5 Bids Farewell to Lower School With Traditional Red Sweater Toss": "https://www.smes.org/page/news-detail?pk=1384344&fromId=289710",
    "Grade 5 Students Conclude Labyrinth Unit with Reflective Walk": "https://www.smes.org/page/news-detail?pk=1383351&fromId=289710",
    "Grade 5 Students Dive Into Water Conservation with Consumption Project": "https://www.smes.org/page/news-detail?pk=1373979&fromId=289710",
    "Grade 7 Students Explore West African Culture Through Guest Speaker": "https://www.smes.org/page/news-detail?pk=1369745&fromId=289710",
    "Grade 7 Students Present Shark Tank Stars During Entrepreneurial Presentations": "https://www.smes.org/page/news-detail?pk=1382768&fromId=289710",
    "Grades K-1 Outdoor Classroom": "https://www.smes.org/academics/lower-school/grades-k-1-outdoor-classroom",
    "Graduation Requirements Inquiries": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Grid View": "http://www.smes.org/page/calendar",
    "Guide to Philanthropy": "https://www.smes.org/support-smes/guide-to-philanthropy",
    "HOT LUNCH PROGRAM": "http://www.smes.org/about/ptf",
    "Happy Birthday St. Margaret's!": "https://www.smes.org/page/news-detail?pk=1368910&nc=23150&fromId=289817",
    "Head of School": "https://www.smes.org/about/head-of-school",
    "Health Center": "http://www.smes.org/student-life/health-and-wellness",
    "Health Office Information": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Health Requirements for Non-St. Margaret's Students Prior To Camp": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Health Requirements for St. Margaret's Students Prior To Camp": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Health and Wellness": "https://www.smes.org/student-life/health-and-wellness",
    "Highlander Excerpt: At St. Margaret’s, Innovation Illuminates the Stage": "https://www.smes.org/page/news-detail?pk=1353640&fromId=289897",
    "Highlander Magazine": "https://www.smes.org/page/about/news/highlander-magazine",
    "History & Social Science": "https://www.smes.org/page/academics/academic-program/academic-departments",
    "How do I contact my child during the day?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "How does friday lunch work?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "How the Early School Empowers Young Learners Through Movement": "https://www.smes.org/page/news-detail?pk=1360174&fromId=290012",
    "How to cancel": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Hunsaker Endowment": "http://www.smes.org/support-smes/endowed-funds",
    "Independence Day - School and Offices Closed": "https://www.smes.org/page/event-detail?pk=20664057&fromId=289703",
    "Independent Senior Project": "https://www.smes.org/academics/upper-school/independent-senior-project",
    "Individual CIF and State Champions": "http://www.smes.org/student-life/athletics/championships-and-awards",
    "Information coming soon!": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Innovation": "https://www.smes.org/innovation",
    "Innovation Stage": "https://www.smes.org/community/summer-at-st-margarets/open-enrollment-camps/innovation-stage",
    "Innovation at St. Margaret's": "https://www.smes.org/innovation/innovation-at-st-margarets",
    "Inquire": "http://www.smes.org/page/admission/connect-with-us",
    "Inquire About a Career at St. Margaret’s": "http://www.smes.org/page/about/employment/employment-inquiry",
    "Institutional Research": "https://www.smes.org/about/institutional-research",
    "Is Summer at St. Margaret's open to the public?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Is my young child ready for camp?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Is your program licensed?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Jason A. Weiss, Bishop's Representative": "http://www.smes.org/about/leadership",
    "Jay Spenuzza '03": "http://www.smes.org/about/leadership",
    "Jeffry Stoddard, Trustee Emeritus": "http://www.smes.org/about/leadership",
    "Jennifer Blount '87, Lower School Principal": "http://www.smes.org/about/leadership",
    "Jered Connon Endowment": "http://www.smes.org/support-smes/endowed-funds",
    "Jerrell Rogers, Director of Human Resources": "http://www.smes.org/about/leadership",
    "Jessica Klausner": "http://www.smes.org/about/leadership",
    "Jonathan Tufo, Executive Director of Advancement": "http://www.smes.org/about/leadership",
    "Juneteenth National Independence Day - School and Offices Closed": "http://www.smes.org/page/event-detail?pk=20664053&fromId=289709",
    "Katie Rodin": "http://www.smes.org/about/leadership",
    "Kindness and Gratitude at St. Margaret's": "https://www.smes.org/page/news-detail?pk=1368912&nc=23150&fromId=289817",
    "LEARN MORE ABOUT ACADEMIC PROGRAMS AT EACH GRADE LEVEL": "https://www.smes.org/page/academics/academic-program/academic-departments",
    "LEARN MORE ABOUT OUR STUDENT COMMUNITY": "https://www.smes.org/page/student-life/student-experience",
    "LEARN MORE ABOUT TARTAN TRANSPORTATION": "https://www.smes.org/page/admission/getting-to-st-margarets",
    "LIBRARY LUNCHEON": "http://www.smes.org/about/ptf",
    "Labor Day - School and Offices Closed": "https://www.smes.org/page/event-detail?pk=23330335&fromId=289703",
    "Language & Literacy": "https://www.smes.org/page/academics/early-school/curriculum",
    "Large Tartan Delegation Attends and Presents at NAIS People of Color Conference": "https://www.smes.org/page/news-detail?pk=1361043&nc=17186&fromId=290027",
    "Last Day of School - Minimum Day": "http://www.smes.org/page/event-detail?pk=20884364&fromId=289709",
    "Late Pick-Up Policy": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Late-Game Heroics Propel Boys Soccer to Quarterfinals": "https://www.smes.org/page/news-detail?pk=1370258&fromId=289710",
    "Leadership": "https://www.smes.org/student-life/leadership",
    "League Championships": "http://www.smes.org/student-life/athletics/championships-and-awards",
    "League Champs! Boys Golf Secures Title After Thrilling Playoff": "https://www.smes.org/page/news-detail?pk=1379236&fromId=289710",
    "Learn More": "https://www.smes.org/student-life/health-and-wellness",
    "Learn More About Student Life at St. Margaret's": "https://www.smes.org/student-life",
    "Learning and Enrichment Center": "http://www.smes.org/student-life/health-and-wellness",
    "Library": "https://www.smes.org/academics/academic-program/library",
    "Library Resources": "http://libguides.smes.org/Library",
    "Lindsay Eres '00, Executive Director of Special Camp": "http://www.smes.org/about/leadership",
    "Lost and Found": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Lower School": "https://www.smes.org/academics/lower-school",
    "Lower School Brings Classic The Aristocats Tale to the Stage": "https://www.smes.org/page/news-detail?pk=1373924&fromId=289710",
    "Lower School Brings Magic to the Stage in Madagascar Jr. Musical Adventure": "https://www.smes.org/page/news-detail?pk=1384642&fromId=289710",
    "Lower School Students Showcase Love of Books in Orange County BOB Tournament": "https://www.smes.org/page/news-detail?pk=1375273&fromId=289710",
    "Lower School Unites for Joyful Color Run Promoting Health and Community": "https://www.smes.org/page/news-detail?pk=1384583&fromId=289710",
    "Lower and Middle School Gear Up Classes": "http://www.smes.org/page/community/summer-at-st-margarets/for-st-margarets-students/gear-up-classes",
    "Lucas Monge Sends Tartan Boys Soccer to CIF-SS Semifinal Game": "https://www.smes.org/page/news-detail?pk=1370843&fromId=289710",
    "Lunch Program": "http://www.smes.org/student-life/health-and-wellness",
    "MS/US Students Shine at Winter Film Festival with Passionate Storytelling": "https://www.smes.org/page/news-detail?pk=1367274&fromId=289710",
    "Make a Gift": "https://www.smes.org/page/online-giving",
    "Marcus D. Hurlbut Endowment for Financial Aid": "http://www.smes.org/support-smes/endowed-funds",
    "Mark Risner '86": "http://www.smes.org/about/leadership",
    "Maseeh Middle School Campus": "https://www.smes.org/academics/middle-school/maseeh-middle-school-campus",
    "Matching Gifts": "http://www.smes.org/page/support-smes/giving",
    "Mathematics": "https://www.smes.org/page/academics/early-school/curriculum",
    "Mattingly Messina '13": "http://www.smes.org/about/leadership",
    "Meet the Team": "https://www.smes.org/community/summer-at-st-margarets/about-summer-at-st-margarets/meet-the-team",
    "Michael Allison, Middle School Principal": "http://www.smes.org/about/leadership",
    "Middle School": "https://www.smes.org/academics/middle-school",
    "Middle School Celebrates 7th Annual Random Acts of Kindness Week": "https://www.smes.org/page/news-detail?pk=1370100&fromId=289710",
    "Middle School Elective Focuses on Lives of Service": "http://www.smes.org/page/news-detail?pk=1297682&fromId=290052",
    "Middle School Play Ichabod! Brings Sleepy Hollow to Life at St. Margaret’s": "https://www.smes.org/page/news-detail?pk=1381316&fromId=289710",
    "Middle School Students Buzz With Excitement in Epic Math Bee": "https://www.smes.org/page/news-detail?pk=1367703&fromId=289710",
    "Middle School Students Host an Interactive Health and Wellness Fair": "https://www.smes.org/page/news-detail?pk=1364050&fromId=289710",
    "Middle School program": "https://www.smes.org/page/academics/middle-school/our-everyday",
    "Mission": "https://www.smes.org/about/mission",
    "Momentum Continues to Build for Tartans Thrive: Campaign for a Common Purpose": "http://www.smes.org/page/news-detail?pk=1311922&fromId=290061",
    "More News": "https://www.smes.org/page/about/news",
    "Morning Care": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Music": "https://www.smes.org/page/academics/early-school/curriculum",
    "NEW FAMILIES PROGRAM": "http://www.smes.org/about/ptf",
    "News": "https://www.smes.org/about/news",
    "Niki Miles '19 and Penn Women's Lacrosse Featured in The Daily Pennsylvanian": "http://www.smes.org/page/news-detail?pk=1282517&nc=17229&fromId=289894",
    "Nikki Imai, Director of Enterprise Technology": "http://www.smes.org/about/leadership",
    "Open Enrollment Camps": "https://www.smes.org/community/summer-at-st-margarets/open-enrollment-camps",
    "Orchestra": "http://www.smes.org/student-life/arts/performing-arts",
    "Our Everyday": "https://www.smes.org/academics/lower-school/our-everyday",
    "Our Everyday is Extraordinary - See the Film!": "https://www.smes.org/page/news-detail?pk=1367059&fromId=289710",
    "Our mission": "https://www.smes.org/about/mission",
    "Outdoor Classroom": "https://www.smes.org/academics/early-school/outdoor-classroom",
    "Overview": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "PARENT COMMUNITY WORKSHOPS - SERVICE PROJECTS": "http://www.smes.org/about/ptf",
    "PARENT UP SPEAKER SERIES": "http://www.smes.org/about/ptf",
    "PHOTOS: Early School Students Capture the Spirit of the Season": "https://www.smes.org/page/news-detail?pk=1362106&fromId=290012",
    "PHOTOS: English IV Students Visit Early School for Fall Fun": "http://www.smes.org/page/news-detail?pk=1306978&fromId=290052",
    "PHOTOS: PTF Parent Up Speaker Series Kicks Off With Sam Kass": "http://www.smes.org/page/news-detail?pk=1300458&fromId=290061",
    "PHOTOS: STEAM Expo Spotlights Joyful Learning at St. Margaret’s": "https://www.smes.org/page/news-detail?pk=1382197&fromId=289710",
    "PHOTOS: Tartans Connect to Support the All-School Service Learning Project": "https://www.smes.org/page/news-detail?pk=1365610&fromId=289710",
    "PTF BOOK FAIR": "http://www.smes.org/about/ptf",
    "PTF BOOK FAIR FAMILY NIGHT": "http://www.smes.org/about/ptf",
    "PTF Grant Enrichment Program": "https://www.smes.org/news-detail?pk=1383419",
    "PTF ONLINE AUCTION": "http://www.smes.org/about/ptf",
    "PTF Winter Coffee Brings Community Together With a Peek Toward Spring": "https://www.smes.org/page/news-detail?pk=1365606&fromId=289710",
    "Parents of Alumni": "https://www.smes.org/alumni/parents-of-alumni",
    "Patrick Bendzick, Assistant Head of School for Health & Well-Being": "http://www.smes.org/about/leadership",
    "Paul C. Westhead, Secretary": "http://www.smes.org/about/leadership",
    "Peer Counselors": "http://www.smes.org/student-life/health-and-wellness",
    "Performing Arts": "https://www.smes.org/student-life/arts/performing-arts",
    "Performing Arts Center": "https://www.smes.org/student-life/arts/performing-arts-center",
    "Personal Fitness and Wellness": "https://www.smes.org/page/academics/academic-program/academic-departments",
    "Personal Fitness and Wellness Program": "http://www.smes.org/student-life/health-and-wellness",
    "Phoebe Larson, Director of Enrollment Management": "http://www.smes.org/about/leadership",
    "Physical Development": "https://www.smes.org/page/academics/early-school/curriculum",
    "Play": "http://www.smes.org/student-life/arts/performing-arts-center",
    "Pre K - Grade 12 Experience": "https://www.smes.org/innovation/experiential-learning/pre-k-grade-12-experience",
    "Preschool": "http://www.smes.org/student-life/arts/visual-arts",
    "Private Instruction": "http://www.smes.org/student-life/arts/performing-arts",
    "Professional Community Dedicates In-Service Day to Centering Joy in DEI Work": "https://www.smes.org/page/news-detail?pk=1353400&nc=17186&fromId=290027",
    "Professional Community Engages in Experiential Learning for In-Service Day": "https://www.smes.org/page/news-detail?pk=1373787&fromId=289710",
    "Programs": "https://www.smes.org/academics/early-school/programs",
    "Read More": "https://www.smes.org/page/news-detail?pk=1384440&fromId=289703",
    "Refresh": "https://www.smes.org/page/about/news",
    "Religion and Philosophy": "https://www.smes.org/page/academics/academic-program/academic-departments",
    "Request Info": "https://www.smes.org/page/admission/connect-with-us",
    "Resources and FAQ's": "https://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Roger Yang": "http://www.smes.org/about/leadership",
    "Ryan Korinke": "http://www.smes.org/about/leadership",
    "Ryan Wood, Director of Communications & Marketing": "http://www.smes.org/about/leadership",
    "SMES Athletics website": "https://www.smes.org/student-life/athletics",
    "STEAM and Technology": "https://www.smes.org/innovation/steam-and-technology",
    "STEM": "https://www.smes.org/page/innovation/stem-and-technology",
    "STEM Endowed Fellowship": "http://www.smes.org/support-smes/endowed-funds",
    "Samuel Corliss": "http://www.smes.org/about/leadership",
    "San Juan Summer Nites Concert": "http://www.smes.org/page/event-detail?pk=24483476&fromId=289709",
    "Sarah E. Chester (1976-2020), Trustee Emeritus": "http://www.smes.org/about/leadership",
    "School Bus Service Information": "http://www.smes.org/page/admission/getting-to-st-margarets",
    "School Calendar": "https://www.smes.org/page/calendar",
    "School Counselor": "http://www.smes.org/student-life/health-and-wellness",
    "School Garden": "https://www.smes.org/innovation/experiential-learning/school-garden",
    "School Leaders Share Insights From St. Margaret’s at National Conferences": "https://www.smes.org/page/news-detail?pk=1353842&fromId=290012",
    "School News": "https://www.smes.org/page/about/news",
    "Science": "https://www.smes.org/page/academics/early-school/curriculum",
    "Securities": "http://www.smes.org/page/support-smes/giving",
    "Select All": "https://www.smes.org/page/about/news",
    "Service Learning": "https://www.smes.org/student-life/service-learning",
    "Shop The Tartan Store": "https://www.smes.org/page/tartan-store",
    "Shopping Cart": "http://www.smes.org/page/tartan-store",
    "Social & Emotional Development": "https://www.smes.org/page/academics/early-school/curriculum",
    "Special Camp": "http://www.smes.org/support-smes/guide-to-philanthropy",
    "Spiritual Education": "http://www.smes.org/student-life/health-and-wellness",
    "Spring 2025": "https://www.smes.org/strategic-plan",
    "St. Margaret's Boys Golf Bests Irvine 199-204": "https://www.smes.org/page/news-detail?pk=1378919&fromId=289710",
    "St. Margaret's Boys Lacrosse Unstoppable in League Play": "https://www.smes.org/page/news-detail?pk=1374830&fromId=289710",
    "St. Margaret's Boys Soccer Shocks Lightning 2-0": "https://www.smes.org/page/news-detail?pk=1367147&fromId=289710",
    "St. Margaret's Boys Volleyball Knocks Off Barons in CIF-SS Opening Round": "https://www.smes.org/page/news-detail?pk=1380460&fromId=289710",
    "St. Margaret's Girls Basketball Punches Postseason Ticket With Win Over Rosary": "https://www.smes.org/page/news-detail?pk=1368399&fromId=289710",
    "St. Margaret's Girls Lacrosse Overpowers Northwood 21-12": "https://www.smes.org/page/news-detail?pk=1376991&fromId=289710",
    "St. Margaret's Lacrosse Programs Successful in Early Tests": "https://www.smes.org/page/news-detail?pk=1373968&fromId=289710",
    "St. Margaret's Mourns the Loss of Former Headmaster Markham B. Campaigne": "https://www.smes.org/page/news-detail?pk=1384442&fromId=289710",
    "St. Margaret's Students Excel at Washington University Chemistry Tournament": "https://www.smes.org/page/news-detail?pk=1377317&fromId=289710",
    "St. Margaret's Track & Field Enjoying Successful Stretch": "https://www.smes.org/page/news-detail?pk=1378451&fromId=289710",
    "St. Margaret's Track & Field Teams Capture Pacific Hills League Titles": "https://www.smes.org/page/news-detail?pk=1381403&fromId=289710",
    "St. Margaret’s Andrea Chou Named Orange County Chemistry Teacher of the Year": "https://www.smes.org/page/news-detail?pk=1383661&fromId=289710",
    "St. Margaret’s Announces First Endowed Chair in Support of Science Department": "https://www.smes.org/page/news-detail?pk=1369086&fromId=289710",
    "St. Margaret’s Emphasizes Player Protection with New Innovative Football Helmet": "https://www.smes.org/page/news-detail?pk=1367447&fromId=289710",
    "St. Margaret’s Fosters Cross-Divisional Connections Through Musical Petting Zoo": "https://www.smes.org/page/news-detail?pk=1380250&fromId=289710",
    "St. Margaret’s Professional Community Shares Expertise at National Conferences": "https://www.smes.org/page/news-detail?pk=1372777&fromId=289710",
    "St. Margaret’s Proudly Presents the Graduating Class of 2025": "https://www.smes.org/page/news-detail?pk=1384823&fromId=289710",
    "St. Margaret’s Recognizes Student Achievement at Upper School Awards Ceremony": "https://www.smes.org/page/news-detail?pk=1381461&fromId=289710",
    "St. Margaret’s Showcase Musical Excellence in 2025 Spring Concert Series": "https://www.smes.org/page/news-detail?pk=1382585&fromId=289710",
    "St. Margaret’s Strategic Plan": "https://www.smes.org/strategic-plan",
    "St. Margaret’s Students Recognized for Remarkable Musical Excellence": "https://www.smes.org/page/news-detail?pk=1359527&fromId=289897",
    "St. Margaret’s Students Shine at 2024 Winter Instrumental and Choral Concert": "https://www.smes.org/page/news-detail?pk=1361855&fromId=289897",
    "Stacey Nicholas, Trustee Emeritus": "http://www.smes.org/about/leadership",
    "State Team Champions and Finalists": "http://www.smes.org/student-life/athletics/championships-and-awards",
    "Stefanie Canright Endowment": "http://www.smes.org/support-smes/endowed-funds",
    "Strategic Plan": "https://www.smes.org/page/strategic-plan",
    "Student Experience": "https://www.smes.org/student-life/student-experience",
    "Student Life": "https://www.smes.org/student-life",
    "Student and Parent Education": "http://www.smes.org/student-life/health-and-wellness",
    "Students Welcomed with Aristocats-Themed Fun Ahead of Lower School Musical": "https://www.smes.org/page/news-detail?pk=1371726&fromId=289710",
    "Suad Elias-Atala": "http://www.smes.org/about/leadership",
    "Summer 2024": "https://www.smes.org/strategic-plan",
    "Summer 2025": "https://www.smes.org/strategic-plan",
    "Summer Institute": "https://www.smes.org/community/summer-institute",
    "Summer Scholars - New for Summer 2025": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Summer at St. Margaret's": "https://www.smes.org/community/summer-at-st-margarets",
    "Summer at St. Margaret’s": "https://www.smes.org/community/summer-at-st-margarets",
    "Support SMES": "https://www.smes.org/support-smes",
    "Susan E. Brown": "http://www.smes.org/about/leadership",
    "TARTAN ANGELS PROGRAM": "http://www.smes.org/about/ptf",
    "TARTAN FAMILY BBQ": "http://www.smes.org/about/ptf",
    "TREE LIGHTING CEREMONY": "http://www.smes.org/about/ptf",
    "TREE TRIMMINGS PROGRAM": "http://www.smes.org/about/ptf",
    "Talented Tartans Take the Stage for Middle School Spelling Bee": "https://www.smes.org/page/news-detail?pk=1365605&fromId=289710",
    "Tania Robertson": "http://www.smes.org/about/leadership",
    "Tartan Alumni": "https://www.smes.org/alumni/tartan-alumni",
    "Tartan Alumni Earning Academic Honors as Student-Athletes": "http://www.smes.org/page/news-detail?pk=1289175&nc=17229&fromId=289894",
    "Tartan Alumni Legacy Endowment": "https://www.smes.org/support-smes/tartan-alumni-legacy-endowment",
    "Tartan Baseball Opens Season With Historic Win": "https://www.smes.org/page/news-detail?pk=1371122&fromId=289710",
    "Tartan Baseball Slips Past Sage Hill 3-1": "https://www.smes.org/page/news-detail?pk=1378407&fromId=289710",
    "Tartan Beach Volleyball Advances in CIF-SS Div. II Playoffs": "https://www.smes.org/page/news-detail?pk=1379091&fromId=289710",
    "Tartan Boys Basketball Tops Portola 70-64": "https://www.smes.org/page/news-detail?pk=1366305&fromId=289710",
    "Tartan Boys Golf Edges Portola 208-209": "https://www.smes.org/page/news-detail?pk=1374543&fromId=289710",
    "Tartan Boys Golf and Volleyball Pick Up Early-Season Victories": "https://www.smes.org/page/news-detail?pk=1371853&fromId=289710",
    "Tartan Boys Lacrosse Handles Foothill in 11-9 Upset Win": "https://www.smes.org/page/news-detail?pk=1377818&fromId=289710",
    "Tartan Boys Soccer Books CIF-SS Finals Spot With 1-0 Victory": "https://www.smes.org/page/news-detail?pk=1371236&fromId=289710",
    "Tartan Boys Soccer Through to Second Round After 1-0 Win Over Segerstrom": "https://www.smes.org/page/news-detail?pk=1370091&fromId=289710",
    "Tartan Boys Tennis Downs Fairmont 11-7": "https://www.smes.org/page/news-detail?pk=1375128&fromId=289710",
    "Tartan Boys Tennis Sinks Diablos 15-3": "https://www.smes.org/page/news-detail?pk=1379232&fromId=289710",
    "Tartan Boys Volleyball Downs Sage Hill in Pacific Coast League Action": "https://www.smes.org/page/news-detail?pk=1373750&fromId=289710",
    "Tartan Community Joyfully Comes Together for All-School Spring Service": "https://www.smes.org/page/news-detail?pk=1374727&fromId=289710",
    "Tartan Dancers Shine at Spring Dance Concerts": "https://www.smes.org/page/news-detail?pk=1380484&fromId=289710",
    "Tartan Equestrian Team Excels at OCIEL Competition": "https://www.smes.org/page/news-detail?pk=1373909&fromId=289710",
    "Tartan Filmmakers Leap into Action Over Spring Break": "https://www.smes.org/page/news-detail?pk=1378199&fromId=289710",
    "Tartan Girls Lacrosse Shuts the Door on Canyon 15-8": "https://www.smes.org/page/news-detail?pk=1381478&fromId=289710",
    "Tartan Lacrosse and Volleyball Programs Set for Postseason Competition": "https://www.smes.org/page/news-detail?pk=1379601&fromId=289710",
    "Tartan Open": "https://www.smes.org/support-smes/tartan-open",
    "Tartan Open Brings Community Together in Support of Financial Aid Program": "https://www.smes.org/page/news-detail?pk=1375384&fromId=289710",
    "Tartan Seniors Honored for Their Pursuit of the Arts in College": "https://www.smes.org/page/news-detail?pk=1378236&fromId=289710",
    "Tartan Spring Athletes Pick up All-CIF and All-County Awards": "https://www.smes.org/page/news-detail?pk=1385325&fromId=289710",
    "Tartan Student Achievements: Academic Decathlon, YoungArts and More!": "https://www.smes.org/page/news-detail?pk=1369728&fromId=289710",
    "Tartan Student Achievements: Chemistry, Photography, Service and More!": "https://www.smes.org/page/news-detail?pk=1384052&fromId=289710",
    "Tartan Surf Secures First League Title Since 2017": "https://www.smes.org/page/news-detail?pk=1374421&fromId=289710",
    "Tartan Surf Team Delivers Results at Scholastic Surf Series": "https://www.smes.org/page/news-detail?pk=1367941&fromId=289710",
    "Tartan Surf Team Shines at State Championships": "https://www.smes.org/page/news-detail?pk=1375437&fromId=289710",
    "Tartan Surf Upends Unbeaten JSerra at Season-Closing Contest": "https://www.smes.org/page/news-detail?pk=1373544&fromId=289710",
    "Tartan Swim Program Wrapping up League Competition with Impressive Results": "https://www.smes.org/page/news-detail?pk=1380491&fromId=289710",
    "Tartan Swimmers Excel at Santa Margarita Invitational": "https://www.smes.org/page/news-detail?pk=1375035&fromId=289710",
    "Tartans Excel at CIF Southern Section Track & Field Championships": "https://www.smes.org/page/news-detail?pk=1383506&fromId=289710",
    "Tartans Impress at Season's First Track & Field Meet": "https://www.smes.org/page/news-detail?pk=1373733&fromId=289710",
    "Tartans Notch Important League Victories": "https://www.smes.org/page/news-detail?pk=1366188&fromId=289710",
    "Tartans Outlast San Juan Hills in Wild 22-20 Win": "https://www.smes.org/page/news-detail?pk=1378924&fromId=289710",
    "Tartans Rally to Pick Up CIF-SS First-Round Win": "https://www.smes.org/page/news-detail?pk=1380712&fromId=289710",
    "Tartans Shine In Sensational Revue’s Show-Stopping Performance": "https://www.smes.org/page/news-detail?pk=1368408&fromId=289710",
    "Tartans Tame Timberwolves 2-1": "https://www.smes.org/page/news-detail?pk=1364799&fromId=289710",
    "Tartans Thrive Capital Campaign": "http://www.smes.org/support-smes/guide-to-philanthropy",
    "Tartans Thrive Update: Progress Continues on the St. Margaret’s Commons": "https://www.smes.org/page/news-detail?pk=1384440&fromId=289710",
    "Technology for Teaching and Learning": "https://www.smes.org/innovation/steam-and-technology/technology-for-teaching-and-learning",
    "The Annual Fund": "https://www.smes.org/support-smes/annual-fund",
    "The Importance of a Healthy School Culture": "https://www.smes.org/page/news-detail?pk=1368911&nc=23150&fromId=289817",
    "The Reverend Canon Robert D. Edwards": "http://www.smes.org/about/leadership",
    "The Reverend Canon Robert Edwards, Head of Chaplains": "http://www.smes.org/about/leadership",
    "The Rt. Rev. John H. Taylor, Chairman": "http://www.smes.org/about/leadership",
    "The Science of Motivating Young People": "https://www.smes.org/page/news-detail?pk=1369085&nc=23150&fromId=289817",
    "The St. Margaret’s Endowment": "https://www.smes.org/support-smes/endowment",
    "The Tartan Alumni Legacy Endowment": "https://www.smes.org/support-smes/tartan-alumni-legacy-endowment",
    "The Tartan Open": "https://www.smes.org/support-smes/tartan-open",
    "The camp or class I want is full. How do waitlist work?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "To The Class of 2025….": "https://www.smes.org/page/news-detail?pk=1385132&nc=23150&fromId=289817",
    "Today": "http://www.smes.org/page/calendar",
    "Tuition and Financial Support": "https://www.smes.org/admission/tuition-and-financial-support",
    "Twelve Tartan Track & Field Athletes Headed to CIF Championships": "https://www.smes.org/page/news-detail?pk=1382607&fromId=289710",
    "US and MS English Students Collaborate to Study the Poetry of Langston Hughes": "https://www.smes.org/page/news-detail?pk=1321483&nc=17186&fromId=290027",
    "Unique Courses": "https://www.smes.org/innovation/unique-courses",
    "Upper School": "https://www.smes.org/academics/upper-school",
    "Upper School Academic (for-credit) Classes": "http://www.smes.org/page/community/summer-at-st-margarets/for-st-margarets-students/upper-school-academics",
    "Upper School Academics": "https://www.smes.org/community/summer-at-st-margarets/for-st-margarets-students/upper-school-academics",
    "Upper School Arts Awards Honor Student Achievement in the Arts": "https://www.smes.org/page/news-detail?pk=1336753&fromId=289897",
    "Upper School Arts Awards Showcase Talented Tartan Artists": "https://www.smes.org/page/news-detail?pk=1382741&fromId=289710",
    "Upper School Athletic Camps": "http://www.smes.org/page/community/summer-at-st-margarets/for-st-margarets-students/upper-school-athletics",
    "Upper School Athletics": "https://www.smes.org/community/summer-at-st-margarets/for-st-margarets-students/upper-school-athletics",
    "Upper School Celebrates Language and Culture Week at St. Margaret’s": "https://www.smes.org/page/news-detail?pk=1372191&fromId=289710",
    "Upper School Cell Phone Policy": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Upper School Classrooms": "http://www.smes.org/innovation/steam-and-technology/technology-for-teaching-and-learning",
    "Upper School Student Recognized for Environmental Service Initiative": "https://www.smes.org/page/news-detail?pk=1373170&fromId=289710",
    "Upper School Students Discuss AI in Roundtable With Professional Community": "https://www.smes.org/page/news-detail?pk=1378890&fromId=289710",
    "Upper School Students Excel at Model UN Conference": "https://www.smes.org/page/news-detail?pk=1369683&fromId=289710",
    "Upper School Students Represent St. Margaret’s at Science Bowl Competition": "https://www.smes.org/page/news-detail?pk=1372518&fromId=289710",
    "Upper School Students Shine at Pacific Symphony Youth Orchestra Spring Concert": "https://www.smes.org/page/news-detail?pk=1375129&fromId=289710",
    "Upper School Student’s Service Project Spotlighted in Los Angeles Times": "https://www.smes.org/page/news-detail?pk=1364522&fromId=289710",
    "Upper School Summer Scholars": "https://www.smes.org/community/summer-at-st-margarets/for-st-margarets-students/upper-school-summer-scholars",
    "Upper School Tartan Dancers Perform at the Happiest Place on Earth": "https://www.smes.org/page/news-detail?pk=1379819&fromId=289710",
    "VIDEO: Upper School Senior Shares the Joy of Innovation at St. Margaret's": "http://www.smes.org/page/news-detail?pk=1310191&fromId=290052",
    "Varsity Football 7on7 Game": "http://www.smes.org/page/team-detail?Team=171537&fromId=289709",
    "Victoria L. Otterbein": "http://www.smes.org/about/leadership",
    "View the Interactive College Matriculation Map": "https://www.smes.org/academics/academic-program/college-counseling/college-matriculation-map",
    "Visitors": "https://www.smes.org/student-life/athletics/visitors",
    "Visual Arts": "https://www.smes.org/student-life/arts/visual-arts",
    "Visual Arts Center": "https://www.smes.org/student-life/arts/visual-arts-center",
    "WELCOME BACK COFFEE": "http://www.smes.org/about/ptf",
    "Washington University Chemistry Tournament": "https://www.smes.org/news-detail?pk=1377317",
    "We Get To Do This!": "https://www.smes.org/page/news-detail?pk=1368924&nc=23150&fromId=289817",
    "Welcome": "https://www.smes.org/admission/welcome",
    "What  is the nut policy?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What about sun safety?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What are For SMES Student Programs?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What are Open-Enrollment Camps?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What are staff qualifications?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What are the Grade Levels and what do they mean?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What are the registration dates?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What are the registration deadlines?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What happens if my child gets sick or injured while at camp?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What is the late pick-up policy?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "What should children wear to camp?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "When can my child return to camp?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "When should I keep my child home if they are not feeling well?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "Who is authorized to pick up Early School campers?": "http://www.smes.org/community/summer-at-st-margarets/resources-and-faqs",
    "William N. Moseley Endowment for Service Learning": "http://www.smes.org/support-smes/endowed-funds",
    "Winter 2025": "https://www.smes.org/strategic-plan",
    "Winter Dance Concert Spotlights Tartan Talent": "https://www.smes.org/page/news-detail?pk=1360886&fromId=289897",
    "With Student Safety in Mind, St. Margaret’s Upgrades Weather-Tracking Tools": "http://www.smes.org/page/news-detail?pk=1345287&fromId=290061",
    "World Languages": "https://www.smes.org/page/academics/academic-program/academic-departments",
    "You're Invited!": "https://www.smes.org/page/news-detail?pk=1368913&nc=23150&fromId=289817",
    "Yuki Bannai '21 Leads Pitzer College to 2nd Place Finish": "http://www.smes.org/page/news-detail?pk=1325484&nc=17229&fromId=289894",
    "academic": "https://www.smes.org/page/academics/middle-school/curriculum",
    "admission": "https://www.smes.org/admission/welcome",
    "artistic": "https://www.smes.org/page/student-life/arts",
    "at this link": "https://www.smes.org/all-school-service-learning-project",
    "athletic": "https://www.smes.org/page/student-life/athletics",
    "athletics website": "https://www.smes.org/student-life/athletics",
    "click here": "https://www.smes.org/innovation/diversity-equity-and-inclusion",
    "core value of Equity and Inclusion": "https://www.smes.org/about/mission",
    "core values": "https://www.smes.org/about/mission",
    "educational touchpoints and opportunities to serve": "https://www.smes.org/news-detail?pk=1361184",
    "employment page": "https://www.smes.org/about/employment",
    "former USC football player Jake Olson": "https://www.smes.org/news-detail?pk=1351877",
    "goal in the semifinal match": "https://www.smes.org/news-detail?pk=1370843&fromId=289862",
    "home": "https://www.smes.org/",
    "in 2023": "https://www.smes.org/news-detail?pk=1277601",
    "keyboard_arrow_left": "https://www.smes.org/page/about/news",
    "keyboard_arrow_right": "http://www.smes.org/page/calendar",
    "last August": "https://www.smes.org/news-detail?pk=1341210",
    "last year": "https://www.smes.org/news-detail?pk=1277601",
    "leadership programs": "https://www.smes.org/page/student-life/leadership",
    "more than 100 visits with representatives from colleges and universities": "https://www.smes.org/news-detail?pk=1348401",
    "mySMES": "https://my.smes.org",
    "named the building": "https://www.smes.org/news-detail?pk=1256244",
    "presenting": "https://www.smes.org/news-detail?pk=1272819",
    "program": "https://www.smes.org/page/academics/lower-school/curriculum",
    "school website": "https://www.smes.org/",
    "service learning": "https://www.smes.org/student-life/service-learning",
    "seven students who will play intercollegiate athletics": "https://www.smes.org/news-detail?pk=1368628",
    "six students sign to play intercollegiate athletics": "https://www.smes.org/news-detail?pk=1368628",
    "student life": "https://www.smes.org/student-life",
    "this link": "https://www.smes.org/venture-to-serve",
    "three students who will pursue the arts in college": "https://www.smes.org/news-detail?pk=1378236",
    "university life": "https://www.smes.org/academics/college-counseling",
    "www.smes.org/athletics": "http://www.smes.org/athletics",
    "www.smes.org/boxoffice": "http://www.smes.org/boxoffice",
    "www.smeshighlander.org": "http://www.smes.org/page/about/news/www.smeshighlander.org",
}
